[build]
  command = "NETLIFY=true npm run build"
  publish = "dist"

[[redirects]]
  from = "/catalog"
  to = "/catalog.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

